kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Chart.Name }}-role
rules:
- apiGroups: ["","extensions"]
  resources: ["ingresses","configmaps"]
  verbs: ["get", "watch", "list"]
