kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: {{ .Chart.Name }}-role-binding
   namespace: {{ .Values.namespace }}
subjects:
 - kind: ServiceAccount
   name: {{ .Chart.Name }}-service-account
   namespace: {{ .Values.namespace }}
roleRef:
   kind: Role
   name: {{ .Chart.Name }}-role
   namespace: {{ .Values.namespace }}
   apiGroup: rbac.authorization.k8s.io
